"""initial migration

Revision ID: 263db9f43252
Revises: None
Create Date: 2016-06-03 00:49:20.814053

"""

# revision identifiers, used by Alembic.
revision = '263db9f43252'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
