"""initial migration

Revision ID: eaafd1a9588
Revises: None
Create Date: 2016-06-06 23:18:57.798525

"""

# revision identifiers, used by Alembic.
revision = 'eaafd1a9588'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
